Feature 1
agustingodoyc/iOS_Academy_base_project pull request #1
Opened 2022-08-24 21:43 UTC by agustingodoyc

**STORY**
Feature 1
DESCRIPTION
Parse Json on background and add activity indicator
EVIDENCE
<img width="994" alt="image" src="https://user-images.githubusercontent.com/109157659/186527595-5a4cb186-f0ac-46e4-922a-d9dc6c217d1e.png">
<img width="993" alt="image" src="https://user-images.githubusercontent.com/109157659/186527661-2e7347b8-bbee-4161-95c7-afc20375a49c.png">
<img width="995" alt="image" src="https://user-images.githubusercontent.com/109157659/186527711-fcb8ce9a-abca-49ee-ac62-3fb4a68ee466.png">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/109157659/186528285-84d6194c-627f-4368-a45a-7206ec32bd2b.png">
<img width="816" alt="image" src="https://user-images.githubusercontent.com/109157659/186528216-5b104d89-8506-4765-a17c-62889c6907c7.png">
https://user-images.githubusercontent.com/109157659/186528073-22de7fec-1db7-4695-8508-cecea7554958.mp4

2022-08-25 16:52 UTC, ezequielvelezglobant requested changes

2022-08-25 16:52 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/Parser.swift
> +            if let fileLocation = Bundle.main.url(forResource: file, withExtension: "json") {
do not use if let, use guard statement instead.

2022-08-25 16:52 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/Parser.swift
> +                }
this is repetitive and should not be responsibility of the parse switch to main thread

2022-08-25 16:54 UTC, ezequielvelezglobant commented
Also you need a Module_2/main branch and this PR should point to that branch instead of main.

2022-08-25 17:03 UTC, ezequielvelezglobant commented
Add some Unit Test

2022-08-25 18:59 UTC, agustingodoyc commented on Ted Talk/Ted Talk/Model/Parser.swift
> +                }
https://github.com/agustingodoyc/iOS_Academy_base_project/pull/1/commits#:~:text=Aug%2025%2C%202022-,Feature%201%20fixes%201,-agustingodoyc%20committed%2020

2022-08-25 18:59 UTC, agustingodoyc commented on Ted Talk/Ted Talk/Model/Parser.swift
> +                }
https://github.com/agustingodoyc/iOS_Academy_base_project/pull/1/commits/082cd50052078ed54c57198d523dca6f466dec62

2022-08-25 19:00 UTC, agustingodoyc commented on Ted Talk/Ted Talk/Model/Parser.swift
> +            if let fileLocation = Bundle.main.url(forResource: file, withExtension: "json") {
https://github.com/agustingodoyc/iOS_Academy_base_project/pull/1/commits/b91a34cb2a6dd7e1527efeb5bec967bbbbcde4ea

2022-08-25 20:35 UTC, JMVarelaGlobant requested changes

2022-08-25 20:35 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +            self.activityIndicator.stopAnimating()
It's missing a delay to show the spinner for more time

2022-08-26 20:22 UTC, ezequielvelezglobant requested changes

2022-08-26 20:22 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +    }
if you set a default value, you don't need the `?`.
Also remember never use `!`

2022-08-29 18:29 UTC, agustingodoyc commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +            self.activityIndicator.stopAnimating()
[cfc4e52](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/1/commits/cfc4e52c3ed6b01ae61c5c8bd5f8ad356fe93fa5)

2022-08-29 18:33 UTC, agustingodoyc commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +    }
[46cf05c](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/1/commits/46cf05c6987bf371d5f39861850b2577daf0d291)

2022-08-30 12:44 UTC, JMVarelaGlobant approved these changes

2022-08-30 13:31 UTC, ezequielvelezglobant approved these changes

2022-08-30 17:07 UTC, merged