Create SearchBar and filters
agustingodoyc/iOS_Academy_base_project pull request #3
Opened 2022-09-01 20:59 UTC by agustingodoyc

**STORY**
Create SearchBar and filters
**DESCRIPTION**
Create SearchBar and filters (PickerView)
**EVIDENCE**
![Sep-01-2022 17-58-34](https://user-images.githubusercontent.com/109157659/188011849-e1948bb6-3297-4df2-94ac-29c165f3b5a2.gif)

2022-09-02 15:06 UTC, ezequielvelezglobant requested changes
Please review the UI, the tableView should start right before pickerView

2022-09-02 15:06 UTC, ezequielvelezglobant commented on Ted Talk/Ted TalkTests/Ted_TalkTests.swift
> +    }
Separate into deferents test files, one for parser and other for dataManager

2022-09-02 20:17 UTC, agustingodoyc commented on Ted Talk/Ted TalkTests/Ted_TalkTests.swift
> +    }
[305e3cf](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/3/commits/305e3cf6db927d984a3ad54c50acfef1563a4800)

2022-09-05 12:52 UTC, JMVarelaGlobant requested changes

2022-09-05 12:52 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        return pickerOptions.allCases.count
Use **filters** computed property here to be consistent all around the class

2022-09-05 12:52 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +    }
Same here

2022-09-05 18:19 UTC, agustingodoyc commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +    }
[Fixed Picker](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/3/commits/03aad10796cbbe518724ad3fa2cadaa40e6cbc0e)

2022-09-05 18:19 UTC, agustingodoyc commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        return pickerOptions.allCases.count
[Fixed Picker](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/3/commits/03aad10796cbbe518724ad3fa2cadaa40e6cbc0e)

2022-09-06 14:55 UTC, JMVarelaGlobant approved these changes

2022-09-06 16:56 UTC, ezequielvelezglobant approved these changes

2022-09-06 17:12 UTC, merged