NSURL Session
agustingodoyc/iOS_Academy_base_project pull request #5
Opened 2022-09-08 21:18 UTC by agustingodoyc

**STORY**
Fetch json
**DESCRIPTION**
Fetch json with NSURLSession
**EVIDENCE**
![Sep-08-2022 18-16-59](https://user-images.githubusercontent.com/109157659/189227565-5dc7a035-6e58-4de4-921f-c49dac5bd802.gif)

2022-09-12 13:09 UTC, ezequielvelezglobant requested changes
This PR should be pointing to Module_3/base

2022-09-12 13:09 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Protocols/ServiceProtocol.swift
> +
remove empy lines

2022-09-13 14:17 UTC, ezequielvelezglobant approved these changes

2022-09-13 16:55 UTC, JMVarelaGlobant approved these changes

2022-09-13 16:55 UTC, merged