MVVM refactor
agustingodoyc/iOS_Academy_base_project pull request #6
Opened 2022-09-09 19:07 UTC by agustingodoyc

**STORY**
Refactor to MVVM
**DESCRIPTION**
refactor to MVVM implementation
**EVIDENCE**
<img width="261" alt="image" src="https://user-images.githubusercontent.com/109157659/189424619-67bfa4e3-ffa6-44e9-8ca8-44dcfe10a267.png">
![Sep-09-2022 16-02-12](https://user-images.githubusercontent.com/109157659/189425035-155db3f8-7d8a-457b-8274-b58fbf55ee62.gif)

2022-09-12 13:24 UTC, ezequielvelezglobant requested changes

2022-09-12 13:24 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/FromWebParser.swift
> +class FromWebParser: ServiceProtocol {
Why you rename this to FromWebParser? this is not a good name. If it's getting info from a web service should be name something related to that.

2022-09-12 13:24 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/ViewModel/TableViewModel.swift
> +    func getDataRows() -> Int {
this name is not correct getDataRows represent that you get all the rows, not the number of rows

2022-09-12 13:24 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/View/TableViewController.swift
> +        cell.loadData(.init(viewModel.getCell(indexPath.row)))
the ViewModel should be responsible of create and return a CellModel.

2022-09-12 13:24 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/View/TableViewController.swift
> +            destination.tedTalk = .init(viewModel.getCell(selectedPath.row))
the ViewModel should be responsible of create and return a DetailModel.

2022-09-12 20:26 UTC, agustingodoyc commented on Ted Talk/Ted Talk/View/TableViewController.swift
> +            destination.tedTalk = .init(viewModel.getCell(selectedPath.row))
[c6611af](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/6/commits/c6611af708dc364d8f6621f9ee20997b02ad7d4c)

2022-09-12 20:26 UTC, agustingodoyc commented on Ted Talk/Ted Talk/View/TableViewController.swift
> +        cell.loadData(.init(viewModel.getCell(indexPath.row)))
[c6611af](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/6/commits/c6611af708dc364d8f6621f9ee20997b02ad7d4c)

2022-09-12 20:26 UTC, agustingodoyc commented on Ted Talk/Ted Talk/ViewModel/TableViewModel.swift
> +    func getDataRows() -> Int {
[c6611af](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/6/commits/c6611af708dc364d8f6621f9ee20997b02ad7d4c)

2022-09-12 20:26 UTC, agustingodoyc commented on Ted Talk/Ted Talk/Model/FromWebParser.swift
> +class FromWebParser: ServiceProtocol {
[c6611af](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/6/commits/c6611af708dc364d8f6621f9ee20997b02ad7d4c)

2022-09-13 14:28 UTC, ezequielvelezglobant requested changes

2022-09-13 14:28 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/ViewModel/TableViewModel.swift
> +    var delegate: ViewModelDelegate?
you have to add weak to the delegate to avoid retain cycles!

2022-09-13 18:33 UTC, agustingodoyc commented on Ted Talk/Ted Talk/ViewModel/TableViewModel.swift
> +    var delegate: ViewModelDelegate?
[d93d09f](https://github.com/agustingodoyc/iOS_Academy_base_project/pull/6/commits/d93d09ffb4c04db5a18a16d62902995816907d3f)

2022-09-14 11:07 UTC, JMVarelaGlobant requested changes
Please fix errors on ParseTest. Every time before pushing your changes to remote, you need to run the tests to ensure your changes don't break anything in your app

2022-09-14 13:04 UTC, ezequielvelezglobant approved these changes

2022-09-15 19:16 UTC, ezequielvelezglobant approved these changes

2022-09-16 12:31 UTC, JMVarelaGlobant approved these changes

2022-09-16 12:31 UTC, merged